# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "api/tests/**/*"
  - "api/alembic/**/*"
  - "api/scripts/**/*"
  - "**/__pycache__/**"
  - "**/*.pyc"

flags:
  unittests:
    paths:
      - api/src/
    carryforward: true
  integration:
    paths:
      - api/src/
    carryforward: true
