import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReportAuditTrail } from "../ReportAuditTrail";
import { ToastProvider } from "@/components/Toast";
import type { ReportAuditEntry } from "@/types/report";

const mockUseReportAuditTrail = vi.fn();

vi.mock("@/hooks/useReports", () => ({
  useReportAuditTrail: (...args: unknown[]) => mockUseReportAuditTrail(...args),
}));

const queryClient = new QueryClient({
  defaultOptions: { queries: { retry: false } },
});

const Wrapper = ({ children }: { children: React.ReactNode }) => (
  <QueryClientProvider client={queryClient}>
    <ToastProvider>{children}</ToastProvider>
  </QueryClientProvider>
);

const mockEntries: ReportAuditEntry[] = [
  {
    id: "entry-1",
    report_type: "CPR Format 1",
    generated_at: "2026-01-15T10:30:00Z",
    generated_by: "admin@example.com",
    parameters: {},
  },
  {
    id: "entry-2",
    report_type: "CPR Format 5",
    generated_at: "2026-01-20T14:00:00Z",
    generated_by: "pm@example.com",
    parameters: {},
  },
];

describe("ReportAuditTrail", () => {
  beforeEach(() => {
    queryClient.clear();
    vi.clearAllMocks();
  });

  it("shows loading state", () => {
    mockUseReportAuditTrail.mockReturnValue({
      data: undefined,
      isLoading: true,
      error: null,
    });

    render(<ReportAuditTrail programId="prog-1" />, { wrapper: Wrapper });

    expect(screen.getByText("Loading audit trail...")).toBeInTheDocument();
  });

  it("shows error state", () => {
    mockUseReportAuditTrail.mockReturnValue({
      data: undefined,
      isLoading: false,
      error: new Error("Failed to load"),
    });

    render(<ReportAuditTrail programId="prog-1" />, { wrapper: Wrapper });

    expect(screen.getByText("Error loading audit trail")).toBeInTheDocument();
  });

  it("shows empty state when no entries", () => {
    mockUseReportAuditTrail.mockReturnValue({
      data: [],
      isLoading: false,
      error: null,
    });

    render(<ReportAuditTrail programId="prog-1" />, { wrapper: Wrapper });

    expect(screen.getByText("No audit entries")).toBeInTheDocument();
  });

  it("renders audit trail table with entries", () => {
    mockUseReportAuditTrail.mockReturnValue({
      data: mockEntries,
      isLoading: false,
      error: null,
    });

    render(<ReportAuditTrail programId="prog-1" />, { wrapper: Wrapper });

    // Column headers
    expect(screen.getByText("Report Type")).toBeInTheDocument();
    expect(screen.getByText("Generated At")).toBeInTheDocument();
    expect(screen.getByText("Generated By")).toBeInTheDocument();

    // Row data
    expect(screen.getByText("CPR Format 1")).toBeInTheDocument();
    expect(screen.getByText("CPR Format 5")).toBeInTheDocument();
    expect(screen.getByText("admin@example.com")).toBeInTheDocument();
    expect(screen.getByText("pm@example.com")).toBeInTheDocument();
  });
});
