/**
 * Report audit trail viewer.
 */

import { useReportAuditTrail } from "@/hooks/useReports";

interface ReportAuditTrailProps {
  programId: string;
}

export function ReportAuditTrail({ programId }: ReportAuditTrailProps) {
  const { data, isLoading, error } = useReportAuditTrail(programId);

  if (isLoading) return <div className="p-4 text-gray-500">Loading audit trail...</div>;
  if (error) return <div className="p-4 text-red-500">Error loading audit trail</div>;
  if (!data || data.length === 0) return <div className="p-4 text-gray-500">No audit entries</div>;

  return (
    <div className="bg-white rounded-lg border overflow-hidden">
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-gray-50 border-b">
            <th className="text-left px-4 py-2 text-xs font-medium text-gray-500">Report Type</th>
            <th className="text-left px-4 py-2 text-xs font-medium text-gray-500">Generated At</th>
            <th className="text-left px-4 py-2 text-xs font-medium text-gray-500">Generated By</th>
          </tr>
        </thead>
        <tbody>
          {data.map((entry) => (
            <tr key={entry.id} className="border-b hover:bg-gray-50">
              <td className="px-4 py-2">{entry.report_type}</td>
              <td className="px-4 py-2 text-gray-600">
                {new Date(entry.generated_at).toLocaleString()}
              </td>
              <td className="px-4 py-2 text-gray-600">{entry.generated_by}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
